api-version: '1.13'
author: 'Epicnicity322'
depend: [ EpicPluginLib ]
description: 'Allows rideable entities to swim.'
main: com.epicnicity322.horseswim.HorseSwim
name: 'HorseSwim'
version: '${project.version}'

commands:
  horsereload:
    description: Reloads the plugin's configurations and listeners.
    permission: horseswim.reload

permissions:
  horseswim.reload:
    default: op
    description: Allows access to /horsereload